service: backendchefeniadb
frameworkVersion: '3'
provider:
  name: aws
  environment:
    AWS_RDS_DB_NAME: ${.env:AWS_RDS_DB_NAME}
    AWS_RDS_HOST: ${.env:AWS_RDS_HOST}
    AWS_RDS_PORT: ${.env:AWS_RDS_PORT}
    DOPPLER_CONFIG: ${.env:DOPPLER_CONFIG}
    DOPPLER_ENVIRONMENT: ${.env:DOPPLER_ENVIRONMENT}
    DOPPLER_PROJECT: ${.env:DOPPLER_PROJECT}
    LAMBDA_ACCESS_KEY_ID: ${.env:LAMBDA_ACCESS_KEY_ID}
    LAMBDA_SECRET_ACCESS_KEY: ${.env:LAMBDA_SECRET_ACCESS_KEY}
    MASTER_PASSWORD: ${.env:MASTER_PASSWORD}
    MASTER_USERNAME: ${.env:MASTER_USERNAME}
    RDS_ACCESS_KEY_ID: ${.env:RDS_ACCESS_KEY_ID}
    RDS_SECRET_ACCESS_KEY: ${.env:RDS_SECRET_ACCESS_KEY}
    S3_ACCESS_KEY_ID: ${.env:S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${.env:S3_SECRET_ACCESS_KEY}
    STORAGE_DRIVER: ${.env:STORAGE_DRIVER}
    UPLOAD_BUCKET: ${.env:UPLOAD_BUCKET}
  runtime: nodejs16.x
functions:
  chefenia:
    handler: server.handler
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
    vpc:
      securityGroupIds:
        - sg-0dbcefb21a13db36d
      subnetIds:
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
  migration:
    handler: migration.handler
    vpc:
      securityGroupIds:
        - sg-0dbcefb21a13db36d
      subnetIds:
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
        - subnet-0417f254f0b949e63
plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
