# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: backendchefeniadb

frameworkVersion: '3'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  environment:
    AWS_RDS_DB_NAME: ${.env:AWS_RDS_DB_NAME}
    AWS_RDS_HOST: ${.env:AWS_RDS_HOST}
    AWS_RDS_PORT: ${.env:AWS_RDS_PORT}
    DOPPLER_CONFIG: ${.env:DOPPLER_CONFIG}
    DOPPLER_ENVIRONMENT: ${.env:DOPPLER_ENVIRONMENT}
    DOPPLER_PROJECT: ${.env:DOPPLER_PROJECT}
    LAMBDA_ACCESS_KEY_ID: ${.env:LAMBDA_ACCESS_KEY_ID}
    LAMBDA_SECRET_ACCESS_KEY: ${.env:LAMBDA_SECRET_ACCESS_KEY}
    MASTER_PASSWORD: ${.env:MASTER_PASSWORD}
    MASTER_USERNAME: ${.env:MASTER_USERNAME}
    RDS_ACCESS_KEY_ID: ${.env:RDS_ACCESS_KEY_ID}
    RDS_SECRET_ACCESS_KEY: ${.env:RDS_SECRET_ACCESS_KEY}
    S3_ACCESS_KEY_ID: ${.env:S3_ACCESS_KEY_ID}
    S3_SECRET_ACCESS_KEY: ${.env:S3_SECRET_ACCESS_KEY}
    STORAGE_DRIVER: ${.env:STORAGE_DRIVER}
    UPLOAD_BUCKET: ${.env:UPLOAD_BUCKET}
  runtime: nodejs16.x

# The `functions` block defines what code to deploy
functions:
  chefenia:
    handler: handler.lambda
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /{any+}
          method: any
          cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
